export const ResponseMessages = {
  SUCCESS: 'Request successful!',
  CREATED: 'Resource successfully created!',
  BAD_REQUEST: 'Bad request! Please check your data.',
  NOT_FOUND: 'Resource not found.',
  INTERNAL_SERVER_ERROR: 'Something went wrong! Please try again later.',
  UNAUTHORIZED: 'Unauthorized access!',
  CONFLICT: 'Conflict! Resource already exists.',
  FORBIDDEN: 'Forbidden! You do not have permission to access this resource.',
  UNPROCESSABLE_ENTITY: 'Unprocessable entity! Please check your data.',
  NO_CONTENT: 'No content!',
  INVALID_CREDENTIALS: 'Invalid credentials!',
  USER_NOT_FOUND: 'User not found!',
  USER_ALREADY_EXISTS: 'User already exists!',
  INVALID_TOKEN: 'Invalid token!',
  TOKEN_EXPIRED: 'Token expired!',
  INVALID_PASSWORD: 'Invalid password!',
  INVALID_EMAIL: 'Invalid email format!',
  EMAIL_NOT_FOUND: 'Email not found!',
  EMAIL_ALREADY_EXISTS: 'Email already exists!',
  INVALID_PHONE: 'Invalid phone number!',
  PHONE_NOT_FOUND: 'Phone number not found!',
  PHONE_ALREADY_EXISTS: 'Phone number already exists!',
};
